### ISSUE TITLE
slow-odgi: Make a little top-level CLI

### ISSUE THREAD

**Issue by sampsyo** [cucapra/pollen#33]
This is purely a quality-of-life thing, but it would be cool to make a top-level CLI entry point for the `slow-odgi` commands. In particular, what is currently `python3 slow_odgi/flip.py` could become `slow-odgi flip`, i.e., we'd make an installable executable called `slow-odgi` with several subcommands.

The concrete steps for this would be:

* Add an `__init__.py` to the `slow_odgi` directory to make it into a Python package.
* Adjust the imports in `slow_odgi/*.py` to use package-relative imports. For example, use `from . import mygfa` instead of `import mygfa`.
* Somewhere (in `__init__.py` or a new `__main__.py`), make a new main function that dispatches to all of the various algorithms. [argparse](https://docs.python.org/3/library/argparse.html) supports subcommands; we could also try [Click](https://click.palletsprojects.com/en/8.1.x/) instead.
* Add metadata to make the `slow_odgi` package installable (with an executable). As you probably know, my favorite tool for this is [Flit](https://flit.pypa.io), but there are other options available.

Probably best to ignore this until after #29 and #31 are merged.

**Comment by anshumanmohan** [comment]
Other high-level things that should also be done after merging:
- [ ] Since beginning to write slow-odgi, I have discovered how to pipe odgi commands. Do that more; cut down on the number of temp files. Maybe this will let me avoid the [temp storm](https://github.com/cucapra/pollen/pull/29#issuecomment-1475035981) I sometimes have, where temp files created when testing one command then become _targets_ for the next command.
- [ ] Test against more of the graphs that are already in the odgi repo. I presume the present selection that we fetch with `make fetch` have been chosen because they are of a reasonable size? @susan-garry?
- [ ] The graphs that we fetch frequently fail to actually test odgi commands rigorously. I have in the back of my mind a bit of a zoo of small graphs that could be added, either to the odgi repo or elsewhere, that, when tested against, would run the commands through their paces.
- [ ] Refactor! There is some known duplication across branches, and sometimes I have done the same thing in different ways in different commands.

**Comment by anshumanmohan** [comment]
Going to wait until #48 lands, since this will create a large diff and create further opportunities for tidying!
