### ISSUE TITLE
`odgi validate` crashing on large graphs

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#81]
Running 
```
make clean
make og
turnt --env validate_oracle test/*.og
```
gives me exit code 134 for the larger files, and, on running in verbose mode, a complaint about the utf-8 encoding. 

Seems strange, since it works okay when I run
```
make clean
make fetch
turnt --env validate_oracle test/*.gfa
```
That is, letting odgi do an on-the-fly conversion from .gfa to .og works out okay.

**Comment by sampsyo** [comment]
Here's what `turnt -vp --env validate_oracle test/*.og` prints for me:

```
$ odgi build -g DRB1-3123.og -o - | odgi validate -i - 2>&1
Missing value at GFA line: S
                            !b6T?l
                                  P1
warning [libhandlegraph]: Serialized object does not appear to match deserialzation type.
warning [libhandlegraph]: It is either an old version or in the wrong format.
warning [libhandlegraph]: Attempting to load it anyway. Future releases will reject it!
libc++abi: terminating due to uncaught exception of type std::runtime_error: Error rewinding to load non-magic-prefixed SerializableHandleGraph
/bin/sh: line 1: 12560 Done(1)                 odgi build -g DRB1-3123.og -o -
     12561 Abort trap: 6           | odgi validate -i - 2>&1
```

That is, we're running `odgi build -g DRB1-3123.og -o -`, which bails out quickly because `DRB1-3123.og` doesn't look like a GFA file. And indeed; it's not.

It's quite possible I'm missing something, but it seems like the `validate_oracle` Turnt environment is not set up to accept pre-converted `.og` files—just actual GFA files. Is there perhaps a different environment that's supposed to take pre-converted odgi files?

**Comment by anshumanmohan** [comment]
Whoops, you're totally right. It was designed to accept GFAs and I moved to an `.og`-accepting style for uniformity, but then failed to make the change in my turnt config. Easy fix, coming up first thing tomorrow!

**Comment by anshumanmohan** [comment]
Also, good to be reminded of the `-p` flag, especially in combination with `-v`!
