### ISSUE TITLE
`pollen_data_gen`: expand `simple`

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/pollen#96]
Presently:
- `pollen_data_gen depth graph.gfa` matches `exine depth -d graph.gfa -a graph.gfa` with some care. The file generated is `graph.data`, which is what Pollen's depth-accelerator needs. `graph.data` contains precomputed stuff beyond the basic graph, but it also lacks some things fundamental to the graph. As a result, this is a lossy conversion: you cannot travel the roundtrip `graph.gfa <-> graph.data`.
- `pollen_data_gen simple graph.gfa` is just something I dreamed up to put the graph into JSON. It has no connection with any accelerator's needs, nor with `graph.data` described above. However, I think it can be shown to be lossless. 

Goals:
- [x] Leave `pollen_data_gen depth` as it is.
- [ ] Change `pollen_data_gen simple`, expanding its precompute and reformatting its output, so that it becomes a superset of `pollen_data_gen depth`. 
- [ ] Show it to be lossless, i.e., capable of a round trip. 
- [ ] Show that it can be filtered in some way to arrive at `pollen_data_gen depth`.

**Comment by susan-garry** [comment]
I am a bit confused as to what we're currently doing - I agree that the goal should be for the data that we're generating to contain a superset of the data required for node depth, but looking at #102 it seems that, rather than filtering this representation to get what we want for node depth, we're generating two separate representations for our general data representation and for node depth. Ideally, at some point we want one data representation that can be filtered to contain only the data needed for an arbitrary graph query (and resized for a hardware accelerator of arbitrary dimensions). Is this the next step for data generation, or am I just misunderstanding what is happening in the code?
